files:
  - source: /getting-started/*.md
    translation: /%language%/%original_path%/%original_file_name%
  - source: /networks/*.md
    translation: /%language%/%original_path%/%original_file_name%
